name: scorlyai-front

networks:
  scorly-network:
    driver: bridge
    name: scorly-network

services:
  nextjs:
    build: .
    ports:
      - ${APP_PORT_EXPOSE}:3000
    command: pm2-runtime npm -- start
    env_file:
      - .env
    networks:
      - scorly-network
